markdown: rdiscount
highlighter: pygments
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: 熊出没注意
url: http://gkld.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 我的简历
    url: /contact.html

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-weibo
    url: http://weibo.com/gkld
  - class: fa-github
    url: http://github.com/gkld
  - class: fa-google-plus
    url: http://gkld.github.io
  - class: fa-facebook
    url: http://gkld.github.io
  - class: fa-twitter
    url: http://gkld.github.io
  - class: fa-rss
    url: http://gkld.github.io

#作者信息
author:
  link: http://www.zhanxin.info/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: true
  id: gkld
