markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: Welcome to gkld's blog
subTitle: another blog of gkld
url: http://gkld.github.in
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 标签
    url: /tags.html
  - text: 联系我
    url: http://gkld.github.io

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: http://www.zhanxin.info
  - class: fa-facebook
    url: https://www.facebook.com/zhu.jiang.58
  - class: fa-github
    url: http://github.com/gkld
  - class: fa-weibo
    url: http://weibo.com/gkld
  - class: fa-twitter
    url: https://twitter.com/zhujiang_gkld

#作者信息
author:
  link: http://www.zhanxin.info/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
